version: '3'

services:
  conda:
    build: .
    image: conda-test
    hostname: conda
    container_name: conda
    restart: on-failure
    environment:
      - DEBUG: ${{ secrets.DEBUG }}
      - SECRET_KEY: ${{ secrets.SECRET_KEY }}
    command: sh -c "conda run gunicorn -k gevent --workers 4 config.wsgi:application -b 0.0.0.0:8000"
    expose:
      - 8000
    ports:
      - 8000:8000