name: develope applications

on:
  push:
    branches:
      - main

env:
  TARGET_SERVER: server-developer
  SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
  DEBUG: 'True'
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DOCKER_USERNAME: 'behzadazadi2693'
  DOCKER_PASSWORD: $"{{ secrets.DOCKER_PASSWORD }}"
  GITHUB_USERNAME: "CodeCrafters-ir"
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  GITHUB_URL: github.com/CodeCrafters-ir/test-actions.git
  IMAGE_NAME: app-test:v1

jobs:
  test:
    runs-on: self-hosted
    environment: test
    container:
      image: python:slim-bullseye
    steps:
      - name: Run Django tests
        run: |
          pip install django
          python manage.py test

  pull:
    runs-on: self-hosted
    needs: 
      - test
    steps:
      - name: pull from github
        run: |
          echo $DEBUG 
          echo $SUDO_PASSWORD | sudo -Sv
          cd /var/www/test-action
          sudo git pull https://$GITHUB_USERNAME:$GITHUB_TOKEN@$GITHUB_URL

  dockerize:
    runs-on: self-hosted
    needs:
      - pull
    steps:            
      - name: Create image
        run: |
          echo $SUDO_PASSWORD | sudo -Sv
          cd /var/www/test-action
          sudo docker build . -t app-test --no-cache

      - name: Run container
        run: |
          echo $DEBUG
          echo $SUDO_PASSWORD | sudo -Sv
          cd /var/www/test-action
          sudo docker compose down
          sudo docker compose up -d  
          
  push-image:
    runs-on: self-hosted
    needs:
      - dockerize
    steps:
      - name: push image to docker account
        run: |
          echo $SUDO_PASSWORD | sudo -Sv
          sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          sudo docker tag app-test $DOCKER_USERNAME/$IMAGE_NAME
          sudo docker push $DOCKER_USERNAME/$IMAGE_NAME